sfdc-ci-demo/src/objects/Candidate__c.object
<CustomObject>
    <description>Represents an applicant who might apply for one or more positions.</description>
    <fields>
        <fullName>Email__c</fullName>
        <externalId>true</externalId>
        <label>Email</label>
        <type>Email</type>
    </fields>
    <fields>
        <fullName>First_Name__c</fullName>
        <externalId>true</externalId>
        <label>First Name</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Last_Name__c</fullName>
        <externalId>true</externalId>
        <label>Last Name</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <picklist>
            <picklistValues>
                <fullName>New</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>Screen</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Hired</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Rejected</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Keep on File</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>Candidate</label>
    <nameField>
        <displayFormat>C-{00000}</displayFormat>
        <label>Candidate Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Candidates</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

sfdc-ci-demo/src/objects/Job_Application__c.object
<CustomObject>
    <description>Represents a candidate&apos;s application to a position.</description>
    <fields>
        <fullName>Candidate__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Candidate</label>
        <referenceTo>Candidate__c</referenceTo>
        <relationshipLabel>Job Applications</relationshipLabel>
        <relationshipName>R00ND0000001pXIZMA2</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Picklist__c</fullName>
        <label>Status</label>
        <picklist>
            <picklistValues>
                <fullName>New</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>Review Resume</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Phone Screen</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Schedule Interviews</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Extend an Offer</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Hired</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Rejected</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Position__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Position</label>
        <referenceTo>Position__c</referenceTo>
        <relationshipLabel>Job Applications</relationshipLabel>
        <relationshipName>Job_Applications</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Job Application</label>
    <nameField>
        <displayFormat>JA-{00000}</displayFormat>
        <label>Job Application Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Job Applications</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

sfdc-ci-demo/src/objects/Position__c.object
<CustomObject>
    <description>This object stores information about the open job positions at our company.</description>
    <fields>
        <fullName>Close_Date__c</fullName>
        <label>Close Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Max_Pay__c</fullName>
        <label>Max Pay</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Min_Pay__c</fullName>
        <label>Min Pay</label>
        <precision>9</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <picklist>
            <picklistValues>
                <fullName>New Position</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>Pending Approval</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Open - Approved</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Closed - Filled</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Closed - Not Approved</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Closed - Canceled</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>Position</label>
    <nameField>
        <label>Position Title</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Positions</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

sfdc-ci-demo/src/classes/JobApplicationTriggerBL_Test.cls
@isTest
private class JobApplicationTriggerBL_Test {

//Comment IST 20JUL-6.15AM 
	
    static testMethod void insertJobApplication() {
    	Candidate__c newCandidate = new Candidate__c(First_Name__c='New', Last_Name__c='Candidate1', Email__c='new.candidate1@test.com');
    	insert newCandidate;
    	Position__c newPosition = new Position__c(Name='TestPosition', Min_Pay__c=1.00, Max_Pay__c=2.00,Status__c='New Position');
    	insert newPosition;
    	Job_Application__c newJobApplication = new Job_Application__c(Candidate__c=newCandidate.Id, Position__c=newPosition.Id, Picklist__c='Hired');
    	insert newJobApplication;
    	
    	Position__c insertedPosition = [SELECT
    									    Id,
    									    Status__c,
    										Close_Date__c
    								    FROM
    								        Position__c
    								    WHERE
    								        Id = :newPosition.Id];
 		
 		System.assertEquals(insertedPosition.Status__c, 'Closed - Filled');
 		System.assertEquals(insertedPosition.Close_Date__c, Date.today());
    	
    }
    
    
    static testMethod void updateJobApplication() {
    	Candidate__c newCandidate = new Candidate__c(First_Name__c='New', Last_Name__c='Candidate1', Email__c='new.candidate1@test.com');
    	insert newCandidate;
    	Position__c newPosition = new Position__c(Name='TestPosition', Min_Pay__c=1.00, Max_Pay__c=2.00,Status__c='New Position');
    	insert newPosition;
    	Job_Application__c newJobApplication = new Job_Application__c(Candidate__c=newCandidate.Id, Position__c=newPosition.Id, Picklist__c='New');
    	insert newJobApplication;
    	
    	newJobApplication.Picklist__c = 'Hired';
    	update newJobApplication;
    	
    	Position__c insertedPosition = [SELECT
    									    Id,
    									    Status__c,
    										Close_Date__c
    								    FROM
    								        Position__c
    								    WHERE
    								        Id = :newPosition.Id];
 		
 		System.assertEquals(insertedPosition.Status__c, 'Closed - Filled');
 		System.assertEquals(insertedPosition.Close_Date__c, Date.today());
    	
    }
    
    
}