sfdc-ci-demo/src/objects/Job_Application__c.object
<CustomObject>
    <description>Represents a candidate&apos;s application to a position.</description>
    <fields>
        <fullName>Picklist__c</fullName>
        <label>Status</label>
        <picklist>
            <picklistValues>
                <fullName>New</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>Review Resume</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Phone Screen</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Schedule Interviews</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Extend an Offer</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Hired</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Rejected</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Position__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Position</label>
        <referenceTo>Position__c</referenceTo>
        <relationshipLabel>Job Applications</relationshipLabel>
        <relationshipName>Job_Applications</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Job Application</label>
    <nameField>
        <displayFormat>JA-{00000}</displayFormat>
        <label>Job Application Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Job Applications</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

sfdc-ci-demo/src/objects/Position__c.object
<CustomObject>
    <description>This object stores information about the open job positions at our company.</description>
    <fields>
        <fullName>Close_Date__c</fullName>
        <label>Close Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <picklist>
            <picklistValues>
                <fullName>New Position</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>Pending Approval</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Open - Approved</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Closed - Filled</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Closed - Not Approved</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Closed - Canceled</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>Position</label>
    <nameField>
        <label>Position Title</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Positions</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

sfdc-ci-demo/src/classes/JobApplicationTriggerBL.cls
public with sharing class JobApplicationTriggerBL {
	
	public static void closePositionOnHire(List<Job_Application__c> newJobApplications, Map<Id, Job_Application__c> oldJobApplicationsMap){
		Boolean isInsert = false;
		Set<Id> positionIds = new Set<Id>();
		List<Position__c> associatedPositions = new List<Position__c>();
		 
		if(oldJobApplicationsMap==null){
			isInsert = true;
		}
		
		for(Job_Application__c newJobApplication : newJobApplications){
			if(newJobApplication.Picklist__c == 'Hired' && newJobApplication.Position__c != null){
				if(isInsert){
					positionIds.add(newJobApplication.Position__c);
				} else if(newJobApplication.Picklist__c != oldJobApplicationsMap.get(newJobApplication.Id).Picklist__c){
					positionIds.add(newJobApplication.Position__c);
				}
			}
		}
		
		if(positionIds.size()>0){
			associatedPositions = [SELECT 
									   p.Id,
			                           p.Status__c, 
			                           p.Close_Date__c 
			                       FROM 
			                       	   Position__c p
			                       WHERE 
			                           p.Id IN :positionIds];
		}
		
		if(associatedPositions.size()>0){
			for(Position__c associatedPosition:associatedPositions){
				associatedPosition.Close_Date__c = Date.today();
				associatedPosition.Status__c = 'Closed - Filled';
			}
			update associatedPositions;
		}
	}
}